[general]
live_config_reload = true

[font]
size = 12

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[colors]
[colors.primary]
background = '#000000'
foreground = '#ffffff'
